export { useAcceptCookies } from './useAcceptCookies'
export { useCookieConsent } from './useCookieConsent'
export { useCopyToClipboard } from './useCopyToClipboard'
export { useDeviceDetect } from './useDeviceDetect'
export { useLocalStorage } from './useLocalStorage'
export { useReadLocalStorage } from './useReadLocalStorage'
